### ISSUE TITLE
"Unknown command bundle" error running `script/bootstrap`

### ISSUE THREAD

**Issue by kenny-evitt** [atom/electron.atom.io#101]
This is *probably* a stupid error – the cause seems pretty obvious – but I figured I'd throw it out there.

I installed Jekyll – `sudo gem install jekyll` – but I observed the error described in the title.

Installing Bundler – `sudo gem install bundler` – fixed the error.

Obviously, I'm not developing with Ruby on the computer I'm using!

If you agree it's sensible, I'll submit a PR to add a note to install Bundler to the README.

**Comment by thedaniel** [comment]
Yeah, a PR would be nice. Thanks!

**Comment by kenny-evitt** [comment]
@jlord Thanks!
