### ISSUE TITLE
Add Stremio (http://www.strem.io)

### ISSUE THREAD

**Issue by Ivshti** [atom/electron.atom.io#102]
Hi,

I'd like to add Stremio - it's a media center to organize your movies / series / channels and receive notifications about them.

It also allows playback through an Add-ons system - right now it has add-ons for YouTube, Filmon.tv and a third-party add-on for streaming from torrents.

It's a nice tech example because it also uses WebChimera.js, i.e. binds electron with libvlc.

Icon here: http://www.strem.io/images/stremio-logo-small.png

*BTW: according to CONTRIBUTE.md, I should open an issue. Should I PR as well?*

**Comment by thedaniel** [comment]
Feel free to open a PR!

**Comment by Ivshti** [comment]
https://github.com/Stremio/electron.atom.io/tree/add-stremio 
The branch is ready, testing it and then PR-ing

**Comment by jlord** [comment]
Added :pizza: :sparkles: :ship:
