### ISSUE TITLE
Add Wire to apps list

### ISSUE THREAD

**Issue by herrmannplatz** [atom/electron.atom.io#109]
I am glad to add another great electron app that has been released today.

![wire](https://cloud.githubusercontent.com/assets/174685/10824124/64cd6210-7e5f-11e5-835a-d72425202125.png)
[Wire](https://wire.com) is a beautiful and secure messenger and calling app.

Thanks to the electron team for this awesome peace of software.

PR: #108

**Comment by jlord** [comment]
OooO! :sparkles: Thanks!
