### ISSUE TITLE
add Wordpress.com to the app list

### ISSUE THREAD

**Issue by lipis** [atom/electron.atom.io#121]
So it looks like Wordpress.com.app is made using Electron
https://developer.wordpress.com/calypso/

<img width="554" alt="screen shot 2015-12-02 at 00 58 09" src="https://cloud.githubusercontent.com/assets/125676/11518213/cdc7e796-988f-11e5-81ea-a3fda8e56f58.png">

**Comment by jlord** [comment]
Nice! We should wait until we hear from them though, don't want to post things unless people OK it themselves :+1:

**Comment by 50Wliu** [comment]
This has been added in #129.
