### ISSUE TITLE
on small site width, top-level menu looks unaligned

### ISSUE THREAD

**Issue by YuriSolovyov** [atom/electron.atom.io#13]
In this case it could be a plain vertical list.
![screenshot from 2015-04-28 17 20 17](https://cloud.githubusercontent.com/assets/2168518/7371689/2899bc14-edcb-11e4-9101-4f4dcb1296f4.png)

**Comment by sotayamashita** [comment]
@YuriSolovyov I think just vertical list is not good in terms of design. Is there any example of vertical list.

**Comment by YuriSolovyov** [comment]
@sotayamashita GitHub's mobile version?

**Comment by sotayamashita** [comment]
@YuriSolovyov I got it. You are talking about hamburger menu.

**Comment by YuriSolovyov** [comment]
@sotayamashita I'm ok with hamburger if menu transforms niceley into it :)

**Comment by jlord** [comment]
These have been centered :+1:
