### ISSUE TITLE
Add Sync to the app list

### ISSUE THREAD

**Issue by luvtechno** [atom/electron.atom.io#136]
Sync is a business chat tool that will boost productivity for a team, and of course built with Electron for Mac and Windows!

https://www.wantedly.com/sync

<img width="256" alt="sync" src="https://cloud.githubusercontent.com/assets/43811/12545437/945bf72e-c385-11e5-8234-1019a612b5ee.png">

**Comment by jlord** [comment]
Done! Thanks!

**Comment by luvtechno** [comment]
Thank you!
