### ISSUE TITLE
Add Electron logo icon asset

### ISSUE THREAD

**Issue by mnquintana** [atom/electron.atom.io#14]
It would be really helpful to have an SVG of just the Electron logo icon (ie. no text) - [this PR](https://github.com/nodegit/nodegit.github.com/pull/23) could really use it, since [Nodegit's website is currently using Atom's logo](http://www.nodegit.org/) when it should be the Electron logo.

/cc @simurai @jlord

**Comment by kevinsawicki** [comment]
@simurai would you mind adding this to this repo? Maybe just call it `electron-icon.svg` and throw it in `images/`? What do you think?

**Comment by simurai** [comment]
Sure.. added: https://github.com/atom/electron.atom.io/tree/gh-pages/images

Also, as a PNG in case.

**Comment by kevinsawicki** [comment]
Awesome, thanks!
