### ISSUE TITLE
pygments no longer supported

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron.atom.io#142]
After merging #141 I got the following warning email about `pygments` being no longer supported.

>The page build completed successfully, but returned the following warning:

>You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

>  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

>For information on troubleshooting Jekyll see:

>  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

>If you have any questions you can contact us by replying to this email.

**Comment by jlord** [comment]
Oh yeah, I remember that this was happening but wasn't sure when. I've already tested moving to`rouge` so I'll get that PR in :soon:  :rainbow:
