### ISSUE TITLE
Netbeast App 

### ISSUE THREAD

**Issue by luisfpinto** [atom/electron.atom.io#171]
Hello, I have recently created an app of Netbeast project with Electron and I would love to have it on the app list. It is an OpenSource project :smile: 

**Name:** Netbeast

**Description:** Netbeast is an Internet of Things javascript development platform
that empowers developers to easily create and deploy IoT apps. With this application you will be able to run the Netbeast dashboard and let's start installing applications and plugins to control all your smart devices.

**URL:** [netbeast.co](https://netbeast.co/)

**Icon:** [here ](https://raw.githubusercontent.com/netbeast/docs/master/img/NetbeastLogo.png)you can download the full size icon

**Comment by jlord** [comment]
Thanks @luisfpinto! Would you mind opening a pull request to add it? I'd be happy to merge :+1:  Here's an [example](https://github.com/atom/electron.atom.io/pull/172).

**Comment by luisfpinto** [comment]
Done :smile:
