### ISSUE TITLE
Add WhapTk to app list

### ISSUE THREAD

**Issue by iconjone** [atom/electron.atom.io#187]
# WhapTk!

A program that runs a **Desktop Friendly** version of http://whap.tk  I first heard about Electron from **Stremio**, and after that... (A few days with electron, and finally electron boilerplate) I made it!
This website is a resource for students, to learn and prepare for their **AP world history** course. **This website, and app is fully managed by students!**
Now to the app itself.
Depending on the size of the App, different ways to use it will appear.
## If sized landscape, default menus will be used..
![landscape](https://cloud.githubusercontent.com/assets/12628313/13853937/14679c46-ec37-11e5-8b94-e2622798f670.PNG)

## When sized in portrait, a menu similar to Mobile will be used... 
![portrait_closed](https://cloud.githubusercontent.com/assets/12628313/13854134/09365302-ec38-11e5-8eae-37d4e62e9186.PNG)
![portrait_opened](https://cloud.githubusercontent.com/assets/12628313/13854142/0b4a1458-ec38-11e5-8030-ea181374be1a.PNG)

## Here's a gif of it in action!
![gif](https://cloud.githubusercontent.com/assets/12628313/13854317/e208a496-ec38-11e5-92ec-54f19eb19cce.gif)

### Our new icon!
![logo2](https://cloud.githubusercontent.com/assets/12628313/13975732/807c2de0-f086-11e5-9282-24a6493350d5.png)

### Our old icon!
![png](https://cloud.githubusercontent.com/assets/12628313/13854567/21edc7c0-ec3a-11e5-90eb-3ef9ebaea7d9.png)
If needed, I can link the ico file in an email.

-Jonathan Samuel
Contact me at : admin@whap.tk

**Comment by iconjone** [comment]
I'm a noob, and I can't seem to link my website, but the website is http://whap.tk

**Comment by jlord** [comment]
Hiya! I think this icon might not scale down so well because it has lot of imagery and text. Do you think you could get another option?

**Comment by iconjone** [comment]
Sure do you want me to design a new icon?  I'll talk with the team, and we should have one done by tomorrow! (Looking at the designs, you're completely right, mine looks out of place with the others)

**Comment by iconjone** [comment]
Alright So We've finished a new logo!
Here it is:
![logo2](https://cloud.githubusercontent.com/assets/12628313/13975715/59debe3c-f086-11e5-8e58-4327cdb35210.png)
