### ISSUE TITLE
Add 'Hain' to application list

### ISSUE THREAD

**Issue by appetizermonster** [atom/electron.atom.io#190]
I've created an app called 'Hain', An 'alt+space' launcher for Windows with Electron. 
so please add it to app list.
thank you.

https://github.com/appetizermonster/hain

![icon](https://raw.githubusercontent.com/appetizermonster/hain/master/app/images/hain.png)

**Comment by iconjone** [comment]
This is so cool! 
I have a question, on the gif on the Github page there is a keyboard monitor of sorts? Is that part of the app, or something you added for the screenshot?

**Comment by appetizermonster** [comment]
@iconjone that is not a part of my app, it's open sourced keycast app called `KeyCastOW`
you can find it at https://brookhong.github.io/2014/04/28/keycast-on-windows.html

**Comment by zeke** [comment]
Thanks for opening an issue, @appetizermonster! Would you mind submitting a pull request? Here's a doc about how to do that: https://github.com/atom/electron.atom.io/blob/gh-pages/CONTRIBUTING.md#adding-an-app-or-project-to-the-site -- please let me know if you need any help with that.
