### ISSUE TITLE
Translation in Japanese

### ISSUE THREAD

**Issue by sotayamashita** [atom/electron.atom.io#20]
about translation in Japanese

This issue is discussed in [atom/electron Translation in Japanese #1496](https://github.com/atom/electron/issues/1496#event-299421627) before.

**Comment by sotayamashita** [comment]
@keithduncan In Github OSS projects, is there any project which has translated docs ?

**Comment by thedaniel** [comment]
My biggest concern is maintenance - it would be a shame if only the English docs stayed up-to-date.

**Comment by sotayamashita** [comment]
@thedaniel I also think it would be confusing.

**Comment by jlord** [comment]
@sotayamashita—@kevinsawicki mentioned in conversation that perhaps having some guides translated would be good because they'll change less than API docs.

What would be your top picks from the docs to be translated?

**Comment by sotayamashita** [comment]
> @kevinsawicki mentioned in conversation that perhaps having some guides translated would be good because they'll change less than API docs.

I got it. 

>What would be your top picks from the docs to be translated?

I think these guides should be translated first below:

* [Using native Node modules](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md)
* [Debugging the main process](https://github.com/atom/electron/blob/master/docs/tutorial/debugging-main-process.md)

I also want to translate tutorial. If there is Japanese one, they can get started with it easily.

**Comment by sotayamashita** [comment]
@jlord What do you think?

**Comment by jlord** [comment]
@sotayamashita I think that sounds great! 

I'm currently working on having the documentation on the site here, but it will all be sourced from the docs in `atom/electron`. Whenever you're ready you could start a PR for those tutorials over on that repo :sparkles:

**Comment by sotayamashita** [comment]
@jlord How should I translate ? Should I create a directory like `docs-ja` under `atom/electron`?

**Comment by jlord** [comment]
@sotayamashita We'll want to keep everything _within_ the `docs` directory in `atom/electron` because that's what we pull out for the website. I think actually just creating a duplicate markdown file of the english one would be fine. Like so:

```
# original 
docs/tutorial/using-native-node-modules.md
# translated 
docs/tutorial/using-native-node-modules-jp.md
```

How does that sound? Then we'll add a link to the English version letting people know there is a translated option as well.

**Comment by sotayamashita** [comment]
@jlord 

Sound good. I am going to start to translate docs. Thanks for everything.

**Comment by jlord** [comment]
:sparkles: 

Awesome! Will close it here and we'll use the `atom/electron` issue now :+1:
