### ISSUE TITLE
Add Fireball Game Editor to "built on Electron" list

### ISSUE THREAD

**Issue by nantas** [atom/electron.atom.io#21]
Fireball is a game editor built with Electron and Polymer, for creating mobile and HTML5 games.

![fireball-144](https://cloud.githubusercontent.com/assets/344547/7525057/fe242c74-f538-11e4-93bc-b3451716e5a4.png)

- Product Name: Fireball
- Home Page: http://fireball-x.com/en
- Github Repo: https://github.com/fireball-x/fireball

Thanks!

**Comment by jlord** [comment]
Awesome—thanks :sparkles:
