### ISSUE TITLE
Link to Application distribution 404s

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron.atom.io#37]
The `Application distribution` link on http://electron.atom.io/docs/v0.27.0/tutorial/quick-start/ goes to http://electron.atom.io/docs/v0.27.0/tutorial/quick-start/application-distribution.md instead of http://electron.atom.io/docs/v0.27.0/tutorial/application-distribution

/cc @jlord

**Comment by kevinsawicki** [comment]
Originally opened as https://github.com/atom/electron/issues/1856 by @cfjedimaster

**Comment by hokein** [comment]
Also application packaging link on  the Application distribution page (http://electron.atom.io/docs/v0.27.0/tutorial/application-distribution/) is broken, atom/electron#1857.

**Comment by jlord** [comment]
Closed via https://github.com/atom/electron.atom.io/pull/43 :sparkles:

**Comment by agungsawit** [comment]
hy
