### ISSUE TITLE
Dialog documentation doesn't specify which options are required

### ISSUE THREAD

**Issue by cfjedimaster** [atom/electron.atom.io#38]
The dialog doc (http://electron.atom.io/docs/v0.27.0/api/dialog/) for showMessageBox doesn't state what options are required. I ran into this trying to open a box w/o specifying buttons.

**Comment by jlord** [comment]
Thanks @cfjedimaster! The next thing on my list is to go through the docs content itself and make improvements like this :sparkles: Since the content is handle in the Electron repo, atom/electron, I'm going to close the issue here and open one for it there :+1:
