### ISSUE TITLE
Contrast in code blocks is too low for comfort.

### ISSUE THREAD

**Issue by nuclearsandwich** [atom/electron.atom.io#41]
It's really hard to read code example sections like the image below because of contrast issues.
![contrast](https://cloud.githubusercontent.com/assets/358882/7998344/cb6a369e-0b08-11e5-8411-3403e25a592b.png)

This could be one of those things where it looks dandy on Macintosh screens and less dandy on the screens of mere mortals.

**Comment by jlord** [comment]
Agree it can be improved :+1:
