### ISSUE TITLE
Adding PopKey for Desktop project to the Electron website

### ISSUE THREAD

**Issue by fabien-d** [atom/electron.atom.io#57]
### Project name
PopKey for Desktop

### Description
A desktop app for Mac and Windows that allows you to browse and share animated GIFs without opening a browser.

### Website
http://popkey.co/send-gifs

### Logo
![popkey-144](https://cloud.githubusercontent.com/assets/747616/8703701/a9f8ff46-2aec-11e5-9ea0-e454fbb23a78.png)

### Screenshot
![popkey](http://d355z7xw1795ks.cloudfront.net/static/pkstatic/img/desktop/app.png)

**Comment by kevinsawicki** [comment]
Do you work for/on PopKey? We've been asking permission directly before putting the icon on the site.

**Comment by fabien-d** [comment]
I work for PopKey and worked on this project.
