### ISSUE TITLE
Permission to use artwork

### ISSUE THREAD

**Issue by DarkmatterVale** [atom/electron.atom.io#58]
Hi,

I would like to use the following 2 photos on a github pages website ( located in your images folder ):

- fork.png
- os-box.png

Is it alright that I use those photos as-is on a webpage? If so, are there any citations you would like me to provide?

Some background info into my project. I am designing a Natural Language Processing package in Python. To showcase how my library is open-source, I would like to use the fork image. In addition, I would like to use the os-box image to demonstrate that my library is open-source. The name of the project is regex4dummies if you would like to look at it before giving me permission.

Thanks,
Vale Tolpegin

**Comment by jlord** [comment]
Hi :wave: 

This site has an [MIT license](https://github.com/atom/electron.atom.io/blob/gh-pages/LICENSE.md) so you're free to use the images so long as you note somewhere that they have a MIT license and include the copyright:

> Copyright (c) 2015 GitHub Inc.

You can click the link above to read the full contents of the license. Good luck with your project! :pizza:

**Comment by DarkmatterVale** [comment]
Thanks for the clarification!
