### ISSUE TITLE
Add GitBook to featured apps?

### ISSUE THREAD

**Issue by unindented** [atom/electron.atom.io#78]
Just saw that GitBook's desktop app uses Electron under the hood: https://www.gitbook.com/editor

Is it worth adding to the list of featured apps?

**Comment by kevinsawicki** [comment]
@SamyPesse and @AaronO interested in having the GitBook icon on the electron homepage?

**Comment by SamyPesse** [comment]
@kevinsawicki That'd be cool! Thanks!

Here is the application icon:

![icon](https://cloud.githubusercontent.com/assets/845425/9643710/f0d5dc42-51c3-11e5-91c1-91b04cd09277.png)

**Comment by kevinsawicki** [comment]
Icon is now up on http://electron.atom.io/#built-on-electron thanks @SamyPesse

**Comment by SamyPesse** [comment]
Thanks :beers:
