### ISSUE TITLE
Markdown Parser Creates Different Header Links than .com

### ISSUE THREAD

**Issue by jlord** [atom/electron.atom.io#80]
The markdown parser we are using on the site is generating different links from the raw markdown than what the parser on GitHub.com the Website generates :sweat: 

Probably should just start generating the site ourselves and then pushing it up so that we can use all the :gem: gems to make it as close to .com as possible. 

**.com vs electron.atom.io**

`...api/web-view-tag.md#webviewsendchannel-args`
`...api/web-view-tag/#lt-webview-gt-send-channel-args`

See original issue: https://github.com/atom/electron/pull/2495

**Comment by jlord** [comment]
Adding content from an issue opened on `atom/electron` which shares the same root problem, from @learningjs:

> :memo:

> In [browser-window](http://electron.atom.io/docs/v0.33.0/api/browser-window) doc, the instance method [win.close()](http://electron.atom.io/docs/v0.33.0/api/browser-window/#win-close) links to the [Event: 'close'](http://electron.atom.io/docs/v0.33.0/api/browser-window/#event-39-close-39), but looks like the link is [broken](http://electron.atom.io/docs/v0.33.0/api/browser-window/#event-close).

@learningjs Unfortunately it's a problem with our markdown parser on the website generating different header ids than the ones on the github.com. On github.com the "Event: 'close'" heading gets `event-close` as its id and so that's what the docs link to. On the Electron website the same header gets turned into `event-39-close-39` :frowning: 

I'm looking to fix this in the near-ish future.

**Comment by learningjs** [comment]
@jlord Thank you, very well explained :smile:

**Comment by jlord** [comment]
https://github.com/atom/electron/issues/3693

**Comment by jlord** [comment]
Also, a little update here—it's looking like GitHub Pages will be switching to a different default markdown renderer and I've tested it and it does the same links as .com :sparkles: so I'm hoping that happens soon and we'll just switch to that. Otherwise I guess I can build locally and push and not use Pages until they ship that update.

**Comment by jlord** [comment]
Fixed in https://github.com/atom/electron.atom.io/pull/174 :tada:
