### ISSUE TITLE
Platform label not highlighted when there are multiple platform labels

### ISSUE THREAD

**Issue by zcbenz** [atom/electron.atom.io#84]
Example page: http://electron.atom.io/docs/v0.33.0/api/tray/
<img width="608" alt="screen shot 2015-09-21 at 11 06 48 am" src="https://cloud.githubusercontent.com/assets/639601/9984778/e4c3b424-6050-11e5-83a2-391b930bb176.png">

**Comment by jlord** [comment]
Ah, on it! :+1:
