### ISSUE TITLE
Adding Kakapo to featured apps

### ISSUE THREAD

**Issue by bluedaniel** [atom/electron.atom.io#94]
I've created a pull request (https://github.com/atom/electron.atom.io/pull/93) to add my app Kakapo to the featured apps list.

I built Kakapo initially using React + Reflux and then went to see how far I could take the app by creating a native mobile (https://itunes.apple.com/gb/app/kakapo/id1046673139) and desktop (http://www.kakapo.co/app.html#desktop) experience too.

With React Native and Electron, I feel that the future is very bright indeed!

The code is available at https://github.com/bluedaniel/kakapo-app

![kakapo](https://cloud.githubusercontent.com/assets/189383/10497447/d9410050-72bd-11e5-92bb-19242d0928a1.png)

**Comment by kenny-evitt** [comment]
@bluedaniel I think you can close this; your PR was merged.

**Comment by bluedaniel** [comment]
Will do.
