### ISSUE TITLE
Add Zoommy to Apps list

### ISSUE THREAD

**Issue by sharpfuryz** [atom/electron.atom.io#95]
According to guildelines for contributing I created this issue to add our application.

Zoommy - is electron application, which helps customers find free photos from various CC0 and publicdomain photo stocks with pleasure.

Application is based upon electron framework, AngularJS, i spent a lot of time optimizing it.
Distribution via application website: http://zoommyapp.com/ 

Feel free to ask any questions.

![logo_icon 2x](https://cloud.githubusercontent.com/assets/1875643/10524475/786c4cfa-7388-11e5-927b-66e62ca716db.png)

**Comment by jlord** [comment]
Cool, thanks!
